name: Test and coverage check

on:
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]
  push:
    branches: [main]

jobs:
  tests_and_coverage:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: npm install

      - name: Display coverage
        uses: ewjoachim/coverage-comment-action@v1.0.3
        with:
          GITHUB_TOKEN: ${{ github.token }}

